format_version: 10
pipelines:
  framework:
    group: mouse
    materials:
      framework-git:
        git: git@scm.mouse.center:mouse/framework.git
    stages:
      - build:
          jobs:
            test-and-build:
              tasks:
                - exec:
                    command: gradle clean test build
                - exec:
                    command: gradle publish
