format_version: 10
environments:
  k8s:
    pipelines:
      - framework
pipelines:
  framework:
    group: mouse
    materials:
      framework-git:
        git: git@scm.mouse.center:mouse/framework.git
    stages:
      - build:
          jobs:
            test-and-build:
              elastic_profile_id: k8s
              tasks:
                - exec:
                    command: gradle --fail-fast
                    arguments:
                      - clean
                      - build
                      - test
                - exec:
                    command: gradle --fail-fast
                    arguments:
                      - publish
