format_version: 10
environments:
  k8s:
    pipelines:
      - framework
pipelines:
  framework:
    group: mouse
    materials:
      framework-git:
        git: https://scm.mouse.center:1443/mouse/framework.git
        usernaem: builder
        encrypted_password: GIT_BUILDER_PASSWORD
    stages:
      - build:
          jobs:
            test-and-build:
              elastic_profile_id: k8s
              tasks:
                - exec:
                    command: gradle
                    arguments:
                      - clean
                      - build
                      - test
                - exec:
                    command: gradle
                    arguments:
                      - publish
